name: carousel_slider
description: A carousel slider widget, support infinite scroll and custom child widget.
homepage: https://github.com/serenader2014/flutter_carousel_slider
repository: https://github.com/serenader2014/flutter_carousel_slider
version: 4.2.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
